"""add stripe fields and webhook events table

Revision ID: 07dbf5bf6712
Revises: bab267b6f68c
Create Date: 2026-06-09 08:25:30.138679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07dbf5bf6712'
down_revision: Union[str, Sequence[str], None] = 'bab267b6f68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_id'), 'webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_events_stripe_event_id'), 'webhook_events', ['stripe_event_id'], unique=True)
    op.add_column('companies', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('stripe_price_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'stripe_price_id')
    op.drop_column('companies', 'subscription_status')
    op.drop_column('companies', 'stripe_subscription_id')
    op.drop_column('companies', 'stripe_customer_id')
    op.drop_index(op.f('ix_webhook_events_stripe_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
